### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by rey-codev** [luciopaiva/country-codes#1]
Do you have an existing js function that would get the list of countries and their information?

**Comment by luciopaiva** [comment]
Hey @rey-codev this was something I did last year for a personal project and it's definitely missing some documentation... and perhaps a bit of code refactoring.
I can do it in the next few days. I let you know when I have something, ok?

**Comment by luciopaiva** [comment]
@rey-codev I refactored a few things and added a proper example and some documentation that should be sufficient to start playing with it. Please let me know if you have any further questions.
